### ISSUE TITLE
Missing localization on the metrics

### ISSUE THREAD

**Issue by JeromeRiffier** [creagia/nova-percentage-card#1]
Hello,

The "of" in the total values (at the bottom of the card) can't be translated, could you add this please.

Thanks in advance.

**Comment by xmuntane** [comment]
Hello!
You can update the package to the latest version (2.0) to be able to translate the texts.

Check out the [ReadMe](https://github.com/creagia/nova-percentage-card#localization) for instructions

**Comment by GautierDele** [comment]
Thanks a lot @xmuntane !
