### ISSUE TITLE
How to get Resource ID?

### ISSUE THREAD

**Issue by DorZuberi** [creagia/nova-percentage-card#2]
Hello,
I wish to display the percent card on detail page, however I don't see any way to get the current viewed resource so I can query it.

**Comment by xmuntane** [comment]
Hello,
Currently, it is not possible to retrieve the Resource ID.

I will have a look at it and on Monday I will release a new version with this feature.

**Comment by DorZuberi** [comment]
Great thank you!

**Comment by xmuntane** [comment]
Hello,
I just released a new version (2.1.0).

Check out the [ReadMe](https://github.com/creagia/nova-percentage-card#resource-detail-example) for instruccions.

**Comment by DorZuberi** [comment]
Thank you mate!
